#!/bin/bash
export BASHDIR="$HOME/.bash"
export USERSH="$HOME/.usersh"

if [[ -d "$BASHDIR" ]]; then
  rm -rf "$BASHDIR"
fi

git clone "https://github.com/grunwmar/bash-environment.git" "$BASHDIR"

if ! [[ -f "$BASHDIR/bashrc" ]]; then
  echo "$BASHDIR/bashrc not found."
  exit
fi

# cleaning
if ! [[ -d "$USERSH" ]]; then
  cp -a "$BASHDIR/sh/users_dir/." "$USERSH/"
fi

if [[ -f "$HOME/.bashrc" ]]; then
  rm "$HOME/.bashrc"
fi

if [[ -f "$HOME/.bash_login" ]]; then
  rm "$HOME/.bash_login"
fi

if [[ -f "$HOME/.bash_logout" ]]; then
  rm "$HOME/.bash_logout"
fi

# symlinks
ln -s "$BASHDIR/bashrc" "$HOME/.bashrc"
ln -s "$BASHDIR/login" "$HOME/.bash_login"
ln -s "$BASHDIR/logout" "$HOME/.bash_logout"

if [[ -f "$USERSH/profile" ]]; then
  ln -s "$USERSH/profile" "$HOME/.bash_profile"
fi

