#!/bin/bash
PROMPT_COMMAND='PS1_CMD1=$(git branch --show-current 2>/dev/null); if ! [[ -z ${PS1_CMD1} ]]; then PS1_CMD1="[${PS1_CMD1}]"; fi';

PS1='\$\[\e[94m\]$?\[\e[0m\] \[\e[92m\]\u\[\e[92;2m\]@\[\e[92m\]\h\[\e[0m\] \[\e[97m\]\w\[\e[93m\]${PS1_CMD1}\[\e[0m\] '